# Part of this code is sampled (just the auth() function) from google's quickstart docs here : https://developers.google.com/workspace/gmail/api/quickstart/python
# For any future devs of this project: If you need the token, either email the previous dev (easier) or get the credentials 
# For any future programmer (or myself for that matter)
# Credentials: New GMAIL_SERVICE_ACCOUNT_KEY can be created on our Google Cloud on the mechmania email, 
#                                                           under clients -> Oath2 client Ids -> Mechmania email automator
#                       -> The reusable GMAIL_SERVICE_CREDS generated by the script below must be deleted from supabase upon making a new GMAIL_SERVICE_ACCOUNT_KEY 
#                       -> Make sure to go to https://myaccount.google.com/connections and remove MECHMANIA every time you make a new key as well.
#             SUPABASE_URL and SUPABASE_KEY can be created on the supabase URL.


import os.path
from typing import Any, List
from pydantic import BaseModel
from supabase import acreate_client, AsyncClient
from google.auth.transport.requests import Request
from google.oauth2.credentials import Credentials
from google_auth_oauthlib.flow import InstalledAppFlow
from googleapiclient.discovery import build
from googleapiclient.errors import HttpError
import json, os
from dotenv import load_dotenv


#load environment variables
_=load_dotenv('.env')

# load supabase client
url:str = os.environ["SUPABASE_URL"] or ""
key:str = os.environ["SUPABASE_KEY"] or ""

db:AsyncClient = acreate_client(url,key)



#load email client
# If modifying these scopes, delete the file token.json or the token in environment
SCOPES = ["https://www.googleapis.com/auth/gmail.send"]
GMAIL_SERVICE_ACCOUNT_KEY:Any = json.loads(os.environ['GMAIL_SERVICE_ACCOUNT_KEY'] or '{}')

def auth():
  # TODO set token to loaded creds from DB
  """Runs to grab cred to do executive actions"""
  creds = None
  db_data:List[Any] = db.table("tokens").select("value").eq("name","GMAIL_SERVICE_CREDS").execute().data
  try:               Token = db_data[0].get('value')
  except IndexError: Token = None

  if Token:
    creds = Credentials.from_authorized_user_info(json.loads(Token),SCOPES)

  # If there are no (valid) credentials available, let the user log in.

  if not creds or not creds.valid:

    if creds and creds.expired and creds.refresh_token:
      creds.refresh(Request())

    else:
      flow = InstalledAppFlow.from_client_config(GMAIL_SERVICE_ACCOUNT_KEY,SCOPES)
      creds = flow.run_local_server(port=62800, access_type='offline', include_granted_scopes=False)
    # Save the credentials for the next run
    response = (
        db.table("tokens")
        .upsert({"name":"GMAIL_SERVICE_CREDS", "value": creds.to_json()})
        .execute()
    )
     
    
  return creds


class PasswordSubmission(BaseModel):
    password:str

def checkPassword(password:str):
  return password == os.environ['ADMIN_PASSWORD']

